name: waste2ways
description: "Andorid app for waste-2-ways"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  provider: ^6.1.2
  uuid: ^4.5.1
  flutter_lints: ^5.0.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutterfire_cli: ^1.1.0

flutter:

  uses-material-design: true